spring:
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:admin}
    password: ${RABBITMQ_PASSWORD:admin123!@#}
  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL;DATABASE_TO_LOWER=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false
  security:
    cors:
      allowed-origins: ${ALLOWED_ORIGINS}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
  health:
    rabbit:
      enabled: true

springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter : method
    doc-expansion : none

jwt:
  secret-key: random-secret-key-32-byte-1234567890-1234567890
  access-exp: 3600000
  refresh-exp: 86400000

admin:
  username: cocomu
  password: cocomu1!
  swagger:
    url: http://localhost:8080

oauth:
  github:
    client-id: ${GITHUB_ID}
    client-secret: ${GITHUB_SECRET}
  kakao:
    client-id: ${KAKAO_ID}
    client-secret: ${KAKAO_SECRET}
  google:
    client-id: ${GOOGLE_ID}
    client-secret: ${GOOGLE_SECRET}
    redirect-uri: ${GOOGLE_REDIRECT_URI}

---

spring:
  config:
    activate:
      on-profile: local
  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: false
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql

rabbitmq:
  exchange:
    name: ${RABBITMQ_EXCHANGE_NAME:code.execution.exchange}
  routing:
    key: ${RABBITMQ_ROUTING_KEY:code.execution.key}